In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [6]:
with open('./lists/country_names_a_z.pkl', 'rb') as f:
    country_names = pickle.load(f)
country_names = np.array(country_names)
country_names.shape

(180,)

In [7]:
df = pd.read_excel("./data/GDP per capita.xls", sheet_name="data")
df.index = df['Country Name'].values
df.drop(['Country Code', 'Country Name', '2022'], axis=1, inplace=True)
df.head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Aruba,21023.157513,20913.299497,21377.095185,22050.830932,24104.646177,24975.673257,25833.445623,27665.426465,29011.559245,25739.137251,...,25609.955724,26515.678080,26942.307976,28421.386493,28451.273745,29326.708058,30220.594523,31650.760537,24487.863560,29342.100858
Africa Eastern and Southern,707.015752,628.225242,626.580853,812.973645,985.563259,1120.484333,1226.223569,1369.855328,1428.382728,1411.622460,...,1759.182395,1730.394686,1719.183721,1538.552268,1443.692371,1628.586788,1564.734340,1512.270553,1363.540741,1549.772730
Afghanistan,181.000000,125.000000,183.532775,200.462567,221.657604,255.055120,274.000486,375.078128,387.849174,443.845151,...,663.141053,651.987862,628.146804,592.476537,520.252064,530.149831,502.056771,500.522664,516.866552,368.754614
Africa Western and Central,520.786584,529.584939,619.773282,697.905291,841.357961,1000.869581,1241.851900,1417.605050,1681.477680,1463.393293,...,1953.407033,2149.295219,2243.271464,1876.623483,1645.023767,1585.911930,1731.311792,1749.303317,1683.436391,1757.030626
Angola,556.884244,527.463202,872.657772,982.805601,1254.695563,1900.724725,2597.962682,3121.350475,4081.715004,3123.697586,...,4962.552072,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1603.993477,1953.533757

In [41]:
df2 = pd.read_excel("./data/API_NY.GDP.MKTP.CD_DS2_en_excel_v2_5551619.xls", sheet_name="data")
df2.index = df2['Country Name'].values
df2.drop(['Country Name', 'Country Code', '2022'], axis=1, inplace=True)
df2.head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Aruba,1.873184e+09,1.896648e+09,1.962011e+09,2.044134e+09,2.254749e+09,2.359777e+09,2.469832e+09,2.677654e+09,2.843017e+09,2.553631e+09,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09
Africa Eastern and Southern,2.839379e+11,2.588300e+11,2.648815e+11,3.526741e+11,4.388531e+11,5.122337e+11,5.757224e+11,6.608270e+11,7.081192e+11,7.190953e+11,...,9.720022e+11,9.826771e+11,1.003403e+12,9.231439e+11,8.898593e+11,1.030482e+12,1.016697e+12,1.009052e+12,9.341791e+11,1.089454e+12
Afghanistan,NaN,NaN,3.854235e+09,4.539501e+09,5.220824e+09,6.226199e+09,6.971379e+09,9.715762e+09,1.024977e+10,1.215484e+10,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
Africa Western and Central,1.404103e+11,1.467798e+11,1.766058e+11,2.044709e+11,2.534719e+11,3.100942e+11,3.956559e+11,4.644256e+11,5.664795e+11,5.070295e+11,...,7.360399e+11,8.322169e+11,8.924979e+11,7.669580e+11,6.905454e+11,6.837480e+11,7.663597e+11,7.947191e+11,7.847997e+11,8.401873e+11
Angola,9.129595e+09,8.936064e+09,1.528559e+10,1.781270e+10,2.355205e+10,3.697092e+10,5.238101e+10,6.526645e+10,8.853861e+10,7.030717e+10,...,1.249982e+11,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.361907e+10,6.740429e+10

In [2]:
with open("./lists/country_names_a_z.pkl", 'rb') as f:
    country_names = pickle.load(f)
with open('./lists/commodities.pkl', 'rb') as f:
    commodities = pickle.load(f)

In [22]:
dfs = pd.DataFrame(columns=[f"{t}_{j}" for t in range(2000, 2022) for j in commodities.keys()], index=country_names)
dfs

,2000_2,2000_5,2000_7,2000_8,2000_22,2000_27,2000_4,2000_11,2000_28,2000_0,...,2021_6,2021_1,2021_12,2021_21,2021_26,2021_24,2021_3,2021_9,2021_23,2021_25
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Viet Nam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASEAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data = pd.read_excel("./data/commodity_wise_data.xlsx", sheet_name=list(commodities.values()))
data = dict(zip(list(commodities.keys()), list(data.values())))
data.keys()

dict_keys([2, 5, 7, 8, 22, 27, 4, 11, 28, 0, 6, 1, 12, 21, 26, 24, 3, 9, 23, 25])